<a href="https://colab.research.google.com/github/tanyadiwedi78-boop/100_NUMPY-_QUESTIONS/blob/main/ML_IMPORTANT_LIBRARIES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np. __version__)

2.0.2


In [ ]:
# create a null vector of size 10
arr1=np.zeros((10))
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# create a null vector of size 10 but fifth value is 1
z=np.zeros((10))
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# create a 3*3 matrix with values ranging from 0 to 8
a1=np.arange(9).reshape(3,3)
print(a1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# find indices of non-zero elements from [1,2,0,0,4,0]
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [ ]:
# create a identity matriz using eye() of shape 3*3
arr2=np.eye(3)
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# create a 3*3*3 matrix using random
arr3=np.random.random((3,3,3))
print(arr3)


[[[0.95623597 0.85977252 0.00766798]
  [0.41309443 0.08101372 0.38345478]
  [0.38712022 0.47861987 0.48891533]]

 [[0.83971089 0.22939664 0.75662853]
  [0.72668123 0.34707104 0.95159434]
  [0.92710568 0.09275629 0.01110964]]

 [[0.5983721  0.46358488 0.94461226]
  [0.75315594 0.79837882 0.82874992]
  [0.66918117 0.98328372 0.3925004 ]]]


In [ ]:
# create a 10*10 matrix with random and find the minimum and maximum values
import  numpy as np
Z=np.random.random((10,10))
print(f"\n13. Min : {Z.min():.4f},Max: {Z.max():.4f}")



13. Min : 0.0049,Max: 0.9999


In [ ]:
# 14. create a random vector of size 30 and find the mean value
arr_mean=np.random.random(30)
print(f"MEAN : {arr_mean.mean():.4f}")

MEAN : 0.4920


In [ ]:
# 15. create a 2d array with 1 on the border and 0 inside
arr_vec=np.ones((5,5))
arr_vec[1:-1,1:-1]=0
print(arr_vec)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 16. create a border (filled with zeros) around the existing matrix
arr=np.ones((3,3))
arr_pad=np.pad(arr,pad_width=1,mode="constant",constant_values=0)
print(arr_pad)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# 17. what is the result of this expressions?
import numpy as np
print("0 * np.nan:",0 * np.nan)
print("np.nan == np.nan:",np.nan==np.nan)
print("np.inf > np.nan",np.inf > np.nan)
print("np.nan - np.nan",np.nan-np.nan)
print("0.3 == 3*0.1",0.3 == 3*0.1)
print("using np.isclose(0.3,3*0.1)",np.isclose(0.3,3*0.1))


0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan False
np.nan - np.nan nan
0.3 == 3*0.1 False
using np.isclose(0.3,3*0.1) True


In [ ]:
# 18. create a 5*5 matrix with values 1,2,3,4 just below the diagonal where k means 0 means main diagonal 1 means upper diagonal -1 means below diagonal
arr_diag=np.diag([1,2,3,4],k=-1)
print(arr_diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# 18. create a 8*8 matrix anf fill it with a checkerboard pattern with 0
import numpy as np
arr=np.ones((8,8))
arr[1::2, ::2]=0
arr[::2,1::2]=0
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**FEATURE SCALING**

In [ ]:
name=np.array(["Riya","Prasant","Raghav","Yash","Niyati"])
marks=np.array([98,90,56,67,87])
highest=np.argmax(marks)
print(name[highest])

Riya


In [ ]:
import numpy as np
arr=np.random.randn(3,4)
arr1=np.random.randn(4,5)
arr2=np.einsum('ij,jk->ik',arr,arr1)
print(arr2)


[[-0.81773265 -0.71510028 -1.70498509  0.16892449  1.42340695]
 [ 1.3920495  -1.65118663 -3.53616178  2.36091511 -0.38270294]
 [ 1.28515069 -0.49023679 -2.64870774  2.47346357 -1.53615908]]


**RESHAPING**

In [ ]:
# ravel convert any n dimensional array in 1-d array
# transpose any matrix by using np.T
arr=np.arange(10).reshape(5,2)
print(arr.T)
print(np.ravel(arr))


[[0 2 4 6 8]
 [1 3 5 7 9]]
[0 1 2 3 4 5 6 7 8 9]


S**TACKING**

In [ ]:
# np.hstack = horizontal stacking means combine two array as horizontal with same size
import numpy as np
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
arr=np.hstack((a1,a2))
print(arr)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [ ]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
arr=np.vstack((a1,a2))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


**SPILLITING**

In [ ]:
# the inverse process of stacking is spiliting means break two arrays by horizontal means use np.vsplit
arr=np.arange(12).reshape(3,4)
a1=np.hsplit(arr,4)
print(a1)
print(arr)



[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr=np.random.randint(0,12,(3,4)).reshape

print(arr)


[[10  1 11  6]
 [ 0  9  0 10]
 [ 4  9  2  7]]


**FEATURE SCALING**

In [ ]:
# consider a (6,7,8) shape array what is the index (x.y,z) of the 100th element?
import numpy as np
arr1=np.array([[23,45,67,89,12],[23,45,67,78,70]])
arr=np.sort(arr1)
print(arr)
print(arr1.shape)
index_100=np.unravel_index(7,(2,2,2))
print("\n index of 100th element:",index_100)

[[12 23 45 67 89]
 [23 45 67 70 78]]
(2, 5)

 index of 100th element: (np.int64(1), np.int64(1), np.int64(1))


In [ ]:
21. # create checkerboard 8*8 matrix using the tile function
arr_tile=np.tile([3,5] , reps=(2,4))
print("\ncheckerboard using tile function",arr_tile)


checkerboard using tile function [[3 5 3 5 3 5 3 5]
 [3 5 3 5 3 5 3 5]]


In [ ]:
# 22 normalize the 5*5 random matrix (min-max and standarization)
arr_rand=np.arange(50,80).reshape(6,5)
print(arr_rand)

mi,mx=arr_rand.min(),arr_rand.max()
norm=(arr_rand-mi)/(mx-mi) # min-max scaling
print(norm)
# z-score standarization






[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]]
[[0.         0.03448276 0.06896552 0.10344828 0.13793103]
 [0.17241379 0.20689655 0.24137931 0.27586207 0.31034483]
 [0.34482759 0.37931034 0.4137931  0.44827586 0.48275862]
 [0.51724138 0.55172414 0.5862069  0.62068966 0.65517241]
 [0.68965517 0.72413793 0.75862069 0.79310345 0.82758621]
 [0.86206897 0.89655172 0.93103448 0.96551724 1.        ]]


**SIGMOID